name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Or use the branch you're pushing to, like 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Use the Node.js version that your app requires

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages        # Use 'publish_branch' instead of 'deploy_branch'
          publish_dir: build              # Use 'publish_dir' instead of 'folder'
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
